package view;

import dao.UsuarioDao;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author Váleria Matias
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaCadastroUsuario() {
        initComponents();
    }
    
    private void cadastrarNovoUsuario(){
        try{
            
            //Verifica se há espaços vazios nos campos de usuario,login e senha
            if(txtUsuarioNovo.getText().trim().isEmpty()||
               txtLoginNovo.getText().trim().isEmpty()||
               txtSenhaNova.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this,"Preencha todos os campos");
                 return;//se sim, impede de continuar o cadastramento
                
            }
            //pega o perfil selecionado no Combobox
            String perfil = cmbPerfilNovo.getSelectedItem().toString();
            
            //Cria objeto usuario
            Usuario u = new Usuario(
               0,// id gerado automaticamente
               txtUsuarioNovo.getText(),
               txtLoginNovo.getText(),
               txtSenhaNova.getText(),
               perfil 
               );
            
               //inserindo no banco
            new UsuarioDao().inserir(u);
            JOptionPane.showMessageDialog(this,"Usuário cadastrado com sucesso!");
            
               
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Erro ao cadastrar");
        }
    }    
    
    private void voltarAoLogin(){
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtUsuarioNovo = new javax.swing.JTextField();
        lblUsuarioNovo = new javax.swing.JLabel();
        lblSenhaNovo = new javax.swing.JLabel();
        txtSenhaNova = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblLoginNovo = new javax.swing.JLabel();
        txtLoginNovo = new javax.swing.JTextField();
        btnCadastrarNovoUsuario = new javax.swing.JButton();
        lblPerfilNovo = new javax.swing.JLabel();
        btnVoltarAoLogin = new javax.swing.JButton();
        cmbPerfilNovo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        txtUsuarioNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioNovoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 18, 0, 0);
        getContentPane().add(txtUsuarioNovo, gridBagConstraints);

        lblUsuarioNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuarioNovo.setText("Usuário");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 404, 0, 0);
        getContentPane().add(lblUsuarioNovo, gridBagConstraints);

        lblSenhaNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSenhaNovo.setText("Senha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 404, 0, 0);
        getContentPane().add(lblSenhaNovo, gridBagConstraints);

        txtSenhaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaNovaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        getContentPane().add(txtSenhaNova, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("CADASTRAR NOVO USUÁRIO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(150, 400, 0, 393);
        getContentPane().add(jLabel3, gridBagConstraints);

        lblLoginNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoginNovo.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 404, 0, 0);
        getContentPane().add(lblLoginNovo, gridBagConstraints);

        txtLoginNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginNovoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        getContentPane().add(txtLoginNovo, gridBagConstraints);

        btnCadastrarNovoUsuario.setBackground(new java.awt.Color(0, 153, 153));
        btnCadastrarNovoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarNovoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarNovoUsuario.setText("Cadastrar");
        btnCadastrarNovoUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCadastrarNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarNovoUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 99;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 1, 0, 0);
        getContentPane().add(btnCadastrarNovoUsuario, gridBagConstraints);

        lblPerfilNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPerfilNovo.setText("Perfil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 404, 0, 0);
        getContentPane().add(lblPerfilNovo, gridBagConstraints);

        btnVoltarAoLogin.setBackground(new java.awt.Color(0, 102, 102));
        btnVoltarAoLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltarAoLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarAoLogin.setText("Voltar ao login");
        btnVoltarAoLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVoltarAoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAoLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 1, 63, 0);
        getContentPane().add(btnVoltarAoLogin, gridBagConstraints);

        cmbPerfilNovo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Manutenção", "Atendente", "Financeiro", "Visitante" }));
        cmbPerfilNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPerfilNovoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 18, 0, 0);
        getContentPane().add(cmbPerfilNovo, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioNovoActionPerformed

    private void txtSenhaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaNovaActionPerformed

    private void txtLoginNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginNovoActionPerformed

    private void btnCadastrarNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarNovoUsuarioActionPerformed
        cadastrarNovoUsuario();
    }//GEN-LAST:event_btnCadastrarNovoUsuarioActionPerformed

    private void btnVoltarAoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAoLoginActionPerformed
        voltarAoLogin();
    }//GEN-LAST:event_btnVoltarAoLoginActionPerformed

    private void cmbPerfilNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPerfilNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPerfilNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarNovoUsuario;
    private javax.swing.JButton btnVoltarAoLogin;
    private javax.swing.JComboBox<String> cmbPerfilNovo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblLoginNovo;
    private javax.swing.JLabel lblPerfilNovo;
    private javax.swing.JLabel lblSenhaNovo;
    private javax.swing.JLabel lblUsuarioNovo;
    private javax.swing.JTextField txtLoginNovo;
    private javax.swing.JTextField txtSenhaNova;
    private javax.swing.JTextField txtUsuarioNovo;
    // End of variables declaration//GEN-END:variables
}
