package view;

import dao.UsuarioDao;
import javax.swing.JOptionPane;
import model.Usuario;


public class TelaCadastroUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName());

    
    private Usuario usuarioAutenticado;
        
     //construtor que está recebendo o usuario que foi autenticado na tela de login
    public TelaCadastroUsuario(Usuario usuario){
        initComponents();
        this.usuarioAutenticado = usuario;
    }
    
        private void cadastrarNovoUsuario(){
        try{
            
            //Verifica se há espaços vazios nos campos de usuario,login e senha
            if(txtUsuarioNovo.getText().trim().isEmpty()||
               txtLoginNovo.getText().trim().isEmpty()||
               txtSenhaNova.getText().trim().isEmpty()){
                 JOptionPane.showMessageDialog(this,"Preencha todos os campos");
                 return;//se sim, impede de continuar o cadastramento
                
            }
            //pega o perfil selecionado no Combobox
            String perfil = cmbPerfilNovo.getSelectedItem().toString();
            
            //Cria objeto usuario
            Usuario u = new Usuario(
               0,// id gerado automaticamente
               txtUsuarioNovo.getText(),
               txtLoginNovo.getText(),
               txtSenhaNova.getText(),
               perfil 
               );
            
               //inserindo no banco
            new UsuarioDao().inserir(u);
            JOptionPane.showMessageDialog(this,"Usuário cadastrado com sucesso!");
            
               
        } catch(Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Erro ao cadastrar");
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Tela = new javax.swing.JPanel();
        lblUsuarioNovo = new javax.swing.JLabel();
        lblPerfilNovo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuarioNovo = new javax.swing.JTextField();
        btnCadastrarNovoUsuario = new javax.swing.JButton();
        lblLoginNovo = new javax.swing.JLabel();
        txtLoginNovo = new javax.swing.JTextField();
        lblSenhaNovo = new javax.swing.JLabel();
        txtSenhaNova = new javax.swing.JTextField();
        cmbPerfilNovo = new javax.swing.JComboBox<>();
        btnVoltarAoMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        Tela.setBackground(new java.awt.Color(255, 255, 255));
        Tela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUsuarioNovo.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        lblUsuarioNovo.setForeground(new java.awt.Color(0, 102, 102));
        lblUsuarioNovo.setText("Usuário");

        lblPerfilNovo.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        lblPerfilNovo.setForeground(new java.awt.Color(0, 102, 102));
        lblPerfilNovo.setText("Perfil");

        jLabel3.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Cadastro ");

        btnCadastrarNovoUsuario.setBackground(new java.awt.Color(0, 102, 102));
        btnCadastrarNovoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastrarNovoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarNovoUsuario.setText("Cadastar");
        btnCadastrarNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarNovoUsuarioActionPerformed(evt);
            }
        });

        lblLoginNovo.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        lblLoginNovo.setForeground(new java.awt.Color(0, 102, 102));
        lblLoginNovo.setText("Login");

        txtLoginNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginNovoActionPerformed(evt);
            }
        });

        lblSenhaNovo.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        lblSenhaNovo.setForeground(new java.awt.Color(0, 102, 102));
        lblSenhaNovo.setText("Senha");

        cmbPerfilNovo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbPerfilNovo.setForeground(new java.awt.Color(0, 102, 102));
        cmbPerfilNovo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Manutenção", "Atendente", "Financeiro", "Visitante" }));
        cmbPerfilNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPerfilNovoActionPerformed(evt);
            }
        });

        btnVoltarAoMenu.setBackground(new java.awt.Color(0, 102, 102));
        btnVoltarAoMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltarAoMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarAoMenu.setText("Voltar ao menu");
        btnVoltarAoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAoMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelaLayout = new javax.swing.GroupLayout(Tela);
        Tela.setLayout(TelaLayout);
        TelaLayout.setHorizontalGroup(
            TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLayout.createSequentialGroup()
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuarioNovo)
                            .addComponent(lblLoginNovo)
                            .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblSenhaNovo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(TelaLayout.createSequentialGroup()
                                    .addComponent(lblPerfilNovo)
                                    .addGap(50, 50, 50)
                                    .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbPerfilNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtUsuarioNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLoginNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(btnCadastrarNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVoltarAoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TelaLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel3)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        TelaLayout.setVerticalGroup(
            TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuarioNovo)
                    .addComponent(txtUsuarioNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLoginNovo)
                    .addComponent(txtLoginNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaNovo)
                    .addComponent(txtSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerfilNovo)
                    .addComponent(cmbPerfilNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarNovoUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnVoltarAoMenu)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(Tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(Tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logoretangularnova (500 x 400 px).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarAoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAoMenuActionPerformed
        Menu menu = new Menu(usuarioAutenticado);          
        menu.setLocationRelativeTo(this);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarAoMenuActionPerformed

    private void cmbPerfilNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPerfilNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPerfilNovoActionPerformed

    private void txtLoginNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginNovoActionPerformed

    private void btnCadastrarNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarNovoUsuarioActionPerformed
        cadastrarNovoUsuario();
    }//GEN-LAST:event_btnCadastrarNovoUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tela;
    private javax.swing.JButton btnCadastrarNovoUsuario;
    private javax.swing.JButton btnVoltarAoMenu;
    private javax.swing.JComboBox<String> cmbPerfilNovo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLoginNovo;
    private javax.swing.JLabel lblPerfilNovo;
    private javax.swing.JLabel lblSenhaNovo;
    private javax.swing.JLabel lblUsuarioNovo;
    private javax.swing.JTextField txtLoginNovo;
    private javax.swing.JTextField txtSenhaNova;
    private javax.swing.JTextField txtUsuarioNovo;
    // End of variables declaration//GEN-END:variables
}
