/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Váleria Matias
 */
public class TelaRelatorios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRelatorios.class.getName());

    /**
     * Creates new form Telasimulacao
     */
    public TelaRelatorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttipoServico = new javax.swing.JTextField();
        txtStatusServiço = new javax.swing.JTextField();
        txtDataServico = new javax.swing.JTextField();
        lblTipoServico = new javax.swing.JLabel();
        lblTituloServicos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDataServico = new javax.swing.JLabel();
        lblStatusServico = new javax.swing.JLabel();
        lblSepulturaServico = new javax.swing.JLabel();
        txtSepulturaServico = new javax.swing.JTextField();
        btnCadastrarServicos = new javax.swing.JButton();
        btnAtualizarServicos = new javax.swing.JButton();
        btnDeletarServicos = new javax.swing.JButton();
        btnListarServicos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txttipoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoServicoActionPerformed(evt);
            }
        });
        getContentPane().add(txttipoServico);
        txttipoServico.setBounds(189, 69, 196, 22);

        txtStatusServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusServiçoActionPerformed(evt);
            }
        });
        getContentPane().add(txtStatusServiço);
        txtStatusServiço.setBounds(191, 137, 194, 22);

        txtDataServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataServicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataServico);
        txtDataServico.setBounds(191, 103, 194, 22);

        lblTipoServico.setText("Status das Sepulturas:");
        getContentPane().add(lblTipoServico);
        lblTipoServico.setBounds(22, 72, 154, 16);

        lblTituloServicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloServicos.setText("Sistema de Gerenciamento de Cemitérios");
        getContentPane().add(lblTituloServicos);
        lblTituloServicos.setBounds(251, 22, 290, 20);

        jLabel3.setText("Área de Relatórios");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(705, 30, 110, 16);

        jLabel4.setText("Cemitério Descanso Eterno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(31, 25, 143, 16);

        lblDataServico.setText("Períodos dos sepultamentos:");
        getContentPane().add(lblDataServico);
        lblDataServico.setBounds(22, 106, 152, 16);

        lblStatusServico.setText("Concessões prestes a vencer?");
        getContentPane().add(lblStatusServico);
        lblStatusServico.setBounds(22, 140, 154, 16);

        lblSepulturaServico.setText("Serviços realizados");
        getContentPane().add(lblSepulturaServico);
        lblSepulturaServico.setBounds(22, 174, 154, 16);

        txtSepulturaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSepulturaServicoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSepulturaServico);
        txtSepulturaServico.setBounds(191, 171, 194, 22);

        btnCadastrarServicos.setText("Gerar");
        btnCadastrarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarServicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrarServicos);
        btnCadastrarServicos.setBounds(22, 260, 72, 23);

        btnAtualizarServicos.setText("Atualizar");
        btnAtualizarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarServicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtualizarServicos);
        btnAtualizarServicos.setBounds(100, 260, 77, 23);

        btnDeletarServicos.setText("Deletar");
        btnDeletarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarServicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletarServicos);
        btnDeletarServicos.setBounds(183, 260, 72, 23);

        btnListarServicos.setText("Listar");
        btnListarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarServicosActionPerformed(evt);
            }
        });
        getContentPane().add(btnListarServicos);
        btnListarServicos.setBounds(261, 260, 124, 23);

        tblServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lote", "Status", "Tipo da Sepultura", "Data da Criação", "Familiar Responsável", "Serviço Realizado"
            }
        ));
        jScrollPane1.setViewportView(tblServicos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(22, 323, 780, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttipoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoServicoActionPerformed

    private void txtDataServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataServicoActionPerformed

    private void txtStatusServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusServiçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusServiçoActionPerformed

    private void txtSepulturaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSepulturaServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSepulturaServicoActionPerformed

    private void btnDeletarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarServicosActionPerformed

    private void btnCadastrarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarServicosActionPerformed

    private void btnListarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarServicosActionPerformed

    private void btnAtualizarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarServicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRelatorios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarServicos;
    private javax.swing.JButton btnCadastrarServicos;
    private javax.swing.JButton btnDeletarServicos;
    private javax.swing.JButton btnListarServicos;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataServico;
    private javax.swing.JLabel lblSepulturaServico;
    private javax.swing.JLabel lblStatusServico;
    private javax.swing.JLabel lblTipoServico;
    private javax.swing.JLabel lblTituloServicos;
    private javax.swing.JTable tblServicos;
    private javax.swing.JTextField txtDataServico;
    private javax.swing.JTextField txtSepulturaServico;
    private javax.swing.JTextField txtStatusServiço;
    private javax.swing.JTextField txttipoServico;
    // End of variables declaration//GEN-END:variables
}
