package view;


import dao.ServicoDao;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sepultura;
import model.Servico;
import model.Usuario;
import view.Menu;
/**
 *
 * @author Váleria Matias
 */
public class TelaAvisos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAvisos.class.getName());

    /**
     * Creates new form Telasimulacao
     */
    public TelaAvisos() {
        initComponents();
        
    }
    
    private Usuario usuarioAutenticado;
     //construtor que está recebendo o usuario que foi autenticado na tela de login
    public TelaAvisos(Usuario usuario){
        initComponents();
        this.usuarioAutenticado = usuario;
        preencherTabelaAvisos();
        } 
    
    private void preencherTabelaAvisos() {
    DefaultTableModel modeloPendentes = (DefaultTableModel) tblServicosPendentes.getModel();
    DefaultTableModel modeloGeral = (DefaultTableModel) tblAvisosGerais.getModel();
    modeloPendentes.setRowCount(0);
    modeloGeral.setRowCount(0);
    
    ServicoDao sDao = new ServicoDao();

    for (Servico s : sDao.listarTodos()) {
        if(s.getStatusServico().equalsIgnoreCase("Pendente")){
            modeloPendentes.addRow(new Object[]{ 
                s.getIdServico(),
                s.getTipoServico(),
                s.getNotificacaoServico()
            });
        }
        if(s.getNotificacaoServico() != null && !s.getNotificacaoServico().isBlank() ){
            modeloGeral.addRow(new Object[]{ 
                s.getIdServico(),
                s.getTipoServico(),
                s.getStatusServico(),
                s.getNotificacaoServico()
            });

        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicosPendentes = new javax.swing.JTable();
        btnVoltarMenu = new javax.swing.JButton();
        lblAvisosGerais = new javax.swing.JLabel();
        lblTituloServicos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvisosGerais = new javax.swing.JTable();
        lblServicosPendentes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        tblServicosPendentes.setBackground(new java.awt.Color(0, 102, 102));
        tblServicosPendentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        tblServicosPendentes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblServicosPendentes.setForeground(new java.awt.Color(255, 255, 255));
        tblServicosPendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo de Serviço", "Notificação interna"
            }
        ));
        jScrollPane1.setViewportView(tblServicosPendentes);

        btnVoltarMenu.setText("Voltar ao Menu");
        btnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuActionPerformed(evt);
            }
        });

        lblAvisosGerais.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAvisosGerais.setForeground(new java.awt.Color(153, 153, 0));
        lblAvisosGerais.setText("Notificações gerais");

        lblTituloServicos.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        lblTituloServicos.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloServicos.setText("Notificações internas");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cemitério Descanso Eterno");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Área de Avisos");

        tblAvisosGerais.setBackground(new java.awt.Color(0, 102, 102));
        tblAvisosGerais.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        tblAvisosGerais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblAvisosGerais.setForeground(new java.awt.Color(255, 255, 255));
        tblAvisosGerais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo de Serviço", "Status", "Notificação interna"
            }
        ));
        jScrollPane2.setViewportView(tblAvisosGerais);

        lblServicosPendentes.setBackground(new java.awt.Color(255, 255, 255));
        lblServicosPendentes.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblServicosPendentes.setForeground(new java.awt.Color(102, 0, 0));
        lblServicosPendentes.setText("URGENTE: Serviços pendentes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnVoltarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloServicos)
                .addGap(236, 236, 236)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(152, 152, 152))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvisosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblServicosPendentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(lblTituloServicos)
                    .addComponent(btnVoltarMenu))
                .addGap(42, 42, 42)
                .addComponent(lblServicosPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblAvisosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addGap(261, 261, 261))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(usuarioAutenticado);          // nome da sua classe de menu
        menu.setLocationRelativeTo(this);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAvisos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarMenu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvisosGerais;
    private javax.swing.JLabel lblServicosPendentes;
    private javax.swing.JLabel lblTituloServicos;
    private javax.swing.JTable tblAvisosGerais;
    private javax.swing.JTable tblServicosPendentes;
    // End of variables declaration//GEN-END:variables
}
